### ISSUE TITLE
Why does the 1.11 version require forge?

### ISSUE THREAD

**Issue by ActivexDiamond** [CrushedPixel/PixelCamMod#15]
First I apologize if this is in the wrong section, I'm new here and have no idea how this works, my apologies

I thought the other versions didnt require forge. While this isnt a big deal for singleplayer, it is extremely limiting for multiplayer as you need to have forge on the server to play. I really hope you can release a stand alone version

Thanks

**Comment by paolobarbolini** [comment]
I haven't tried forge for minecraft 1.11 yet but unless they removed the ability of a forge client to connect to a vanilla server you should be able to use the pixelcam mod on a server.

**Comment by dordsor21** [comment]
There isn't even a 1.11 version on the plugin

**Comment by CrushedPixel** [comment]
The 1.10 version may be compatible with 1.11, though I'm not sure. Every version of the PixelCamMod so far has needed Forge, and that won't change. It's perfectly possible to join any Minecraft server with Forge clients.

**Comment by ActivexDiamond** [comment]
Oh, I see.
I apologize for my extreme stupidity and lack of information here. It's been a while since I played modded-multiplayer and it appears I've forgotten all my info.
Apologies for the inconvenience.

Thanks to all of you for replying. This is great news
