### ISSUE TITLE
new version??

### ISSUE THREAD

**Issue by lightda104530** [CrushedPixel/PixelCamMod#24]
Will this mod support 1.11.2 or newer version??

**Comment by dwa1275** [comment]
please update for 1.11.2 it works, but tilt does not

**Comment by dwa1275** [comment]
sry, 1.12

**Comment by lightda104530** [comment]
But where can i download it haha...

**Comment by dordsor21** [comment]
I've built the latest version here: http://ci.athion.net/job/PixelCam/ (1.12) @lightda104530
